import Home from './HomePage';
import Products from './ProductsPage';
import SingleProduct from './SingleProductPage';
import About from './AboutPage';
import Cart from './CartPage';
import Error from './ErrorPage';
import Checkout from './CheckoutPage';
import PrivateRoute from './PrivateRoute';
import Login from './Login';
export { Home, Products, SingleProduct, About, Checkout, PrivateRoute, Error, Cart, Login };